### ISSUE TITLE
do subdirs really work in file paths? 

### ISSUE THREAD

**Issue by mbutterick** [AlexKnauth/multi-file-lang#4]
I tried the example from the docs:

```racket

#lang multi-file
--
#file a.rkt
#lang racket/base
(read-line (open-input-file "data/text.txt"))
#file data/text.txt
I'm not code, I'm just text in a text file.
```

And got this error:

```
 open-output-file: cannot open output file
  path: /Users/MB/Desktop/data/text.txt
system error: No such file or directory; errno=2
```

Even though the docs imply that `/Users/MB/Desktop/data/text.txt` should be created.

**Comment by AlexKnauth** [comment]
Ah. I hadn’t realized that about subdirs not existing. Instead of just using `call-with-output-file*` [here](https://github.com/AlexKnauth/multi-file-lang/blob/master/multi-file/lang.rkt#L26), I should be using [`make-parent-directory*`](http://docs.racket-lang.org/reference/Filesystem.html?q=call-with-output-file*#%28def._%28%28lib._racket%2Ffile..rkt%29._make-parent-directory%2A%29%29) first.

**Comment by AlexKnauth** [comment]
Fixed in https://github.com/AlexKnauth/multi-file-lang/commit/21b0cc380f36ffbf26703b27fd12de0d35eb1b82, and tested in https://github.com/AlexKnauth/multi-file-lang/commit/346f982bf702ea550f230fad32520c676fceac76.
